#!/usr/bin/env bash
# Install nginx web server script
sudo apt-get -y update
sudo apt-get -y install nginx
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
