#!/usr/bin/env bash
# Install nginx web server script
# /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# Match and replace
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
# Add 404 Page
echo -e "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/listen 80 default_server/a \terror_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
