#!/usr/bin/env bash
# manage_my_process Bash script

file="/var/run/my_process.pid"
function err()
{
    echo "Usage: manage_my_process {start|stop|restart}"
}

function start()
{
    (./manage_my_process) &
    echo $$ > $file
    echo "manage_py_process started"
}

function stop()
{
    pkill -f ./manage_my_process
    sudo rm $file
    echo "manage_my_process stopped"
}

function restart()
{
    pkill -f ./manage_my_process
    rm $file
    ./manage_my_process &
    echo $$ > $file
    echo "manage_my_process restarted"
}

if [ $# -ne 1 ];
then
    err
else
    case ${1} in
    	"start")
    	    start;;
    	"restart")
    	    restart;;
    	"stop")
    	    stop;;
    	*)
    	    err;;
    esac
fi
